application: ${appengine.app.name}
module: default
version: ${appengine.module.version}
runtime: java
threadsafe: true

public_root: /static

static_files:
  - include: /**

welcome_files:
  - index.html



