# the s~ prefix is related to remote_api config.  See https://developers.google.com/appengine/docs/python/tools/uploadingdata
application: s~${appengine.app.name}
module: api-admin
version: ${appengine.module.version}
runtime: java
threadsafe: true

public_root: /static

static_files:
  - include: /**

welcome_files:
  - index.html

system_properties:
  java.util.logging.config.file: WEB-INF/logging.properties
  
handlers:
  - url: /v1/*
    name: restlet-servlet
    servlet: org.restlet.ext.servlet.ServerServlet
    init_params:
      org.restlet.application: com.getfitivity.webservice.api_admin.application.SampleApplicationn
      # uncomment to enable outbound requests...
      # org.restlet.clients: HTTP HTTPS

  - url: /v1/*
    name: objectify-filter
    filter: com.googlecode.objectify.ObjectifyFilter

  - url: /_ah/remote_api
    name: remote-api
    servlet: com.google.apphosting.utils.remoteapi.RemoteApiServlet